### ISSUE TITLE
Evaluate NetworkManager library for Python

### ISSUE THREAD

**Issue by grunskis** [getsenic/senic-hub#167]
https://github.com/seveas/python-networkmanager

Could replace the brittle mechanism of calling `nmcli` & reading status with notification based approach. Looks like they also support network scanning https://github.com/seveas/python-networkmanager/blob/master/examples/ssids.py

**Comment by luminosuslight** [comment]
Eventually it would be good to switch to this library for Wifi network scanning and connection status checks.

We will probably still need some calls to `nmcli` because we are using the convenience function `nmcli dev wifi con <ssid> password <pw> ifname wlan0 name Bluenet` that takes care of choosing the right security and authentication options and is not available via D-Bus.

**Comment by luminosuslight** [comment]
Replaced all commandline calls with NetworkManager D-Bus library in [this branch](https://github.com/luminosuslight/senic-hub/tree/bluenet_dbus).

Waiting with PR for #194 and addition of python-networkmanager (+fix) in Senic OS.

**Comment by larsblumberg** [comment]
We're now using that library. Great job @luminosuslight!
