### ISSUE TITLE
Add Hub API documentation via swagger-ui for pyramid

### ISSUE THREAD

**Issue by kelada** [getsenic/senic-hub#308]
There is no Hub API documentation, there should be, use [pyramid_swagger](https://github.com/striglia/pyramid_swagger/) or something like it.

@tomster mentioned swagger-ui: [example](http://petstore.swagger.io/) it appears to do the job.

I'm not sure where the best place for this service to run would be, on the hub (only in dev builds)? or on api.senic.com/docs?

**Comment by tomster** [comment]
i vote for generating a static version of the docs via travis and publish them on every commit, instead of running a live service somewhere.

a natural starting point for that could be https://github.com/getsenic/senic-hub/blob/master/travis_after_success.sh where we already upload packages of each successful test run

**Comment by neelotpalnag** [comment]
I'll also implement the Node server in a subsequent commit. Do you recommend it(node server) as a high priority task,
@kelada ?
