### ISSUE TITLE
scan_wifi uses wrong configuration file when provisioned in development mode

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#53]
`cat /etc/supervisor/conf.d/scan_wifi.conf`:

    [program:scan_wifi]
    command = /srv/nuimo_hub/venv/bin/scan_wifi -c /srv/nuimo_hub/production.ini --forever wlan0

**Comment by tomster** [comment]
this is a misunderstanding i think, because actually this is how  it's intended to work.

we try to keep the differences between development and production as small as possible, so here we also want to re-use the supervisor configuration. we achieve this by `pip -e` installing the backend into the production environment, that means, that the console scripts located in the production environment point to the development version.

**Comment by larsblumberg** [comment]
@tomster
