### ISSUE TITLE
Don't deploy to /etc/network/interfaces.available but into senic_hub folder

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#96]
As also discussed with @grunskis, we'd prefer to have all hub specific files in our application folder instead of spreading the files into different (system) directories.

This said, our 2 files in `/etc/network/interfaces.available` (that will be copied to `/etc/network/interfaces.d` by some of our tools) should better be stored somewhere in `/srv/senic_hub`.

@tomster please discus

**Comment by tomster** [comment]
IMHO it's context dependent. i.e. files that are specific to our application (i.e. `production.ini`, the cryptoyaml file etc.) should live inside the project's folder.

in this case, though, they are technically not specific to the hub per-se, but we provide alternative network configurations. the convention for providing alternative configurations is to keep one folder where all the candidates are copied to (i.e. `/usr/local/etc/nginx/sites-available`) and then symlink them into another folder in order to activate them (i.e. `/usr/local/etc/nginx/sites-enabled`) and have the main configuration (i.e. `/usr/local/etc/nginx/nginx.conf`) source that.

anybody debugging connectivity issues on the hub would start looking in `/etc/network/` and not in `/srv/senic_hub`.

i would argue, that the current approach offers the least surprises for users.

**Comment by grunskis** [comment]
The main motivation for creating this ticket was to make the re-provisioning easier. If we store all our things (or most things) in `/srv` then we can easily do `rm -rf /srv` and re-provision the device w/o worrying that there might be other files scattered around the system. 

My proposal is to put all the config related to `senic_hub` in `/srv/senic_hub/etc` for example `/srv/senic_hub/etc/production.ini` or `/srv/senic_hub/etc/supervisor/conf.d/foo.conf` or `/srv/senic_hub/etc/network/interface.d/wlan1` and then either source files from corrsponding config file in `/etc` (supervisor case) or create symlinks from `/srv/...` to `/etc/...` (network configuration case).

**Comment by tomster** [comment]
that makes sense, i've used this approach in other projects already, as well. this is a good example of how requirements change over the life of a project. for deployments that basically only need a single `*.ini` file a separate `etc` is not really needed, but as things start to pile up it makes sense to move it into an `etc` of its own.
