### ISSUE TITLE
Merge users "nuimo" and "senic" into one single user

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/senic-hub#97]

**Comment by tomster** [comment]
i think we should leave it as-is because we still need this user for development, i.e. in the `hub-develop` role. and that user does need write privileges in places where the run user shouldn't have any (but at the same time we don't really want to perform all the development work as `root` because that often has the side-effect of changing file-permissions or ownership accidentally (which then cannot be written or accessed by the run user etc.)

i vote for leaving it as is.

**Comment by larsblumberg** [comment]
I get your point that we should not use root for development – I'm in here.

Can you please elaborate again on the fact why the run user (right now: `nuimo`) should be different from the development user (right now: `senic`). I understand that we want to give the run user as few permissions as possible. But what would happen if an attacker gets the same permissions as the development/deployment user? I.e. if development and run user would be the same?

If we make sure that the development user only has rights to modify certain folders, could the run user then be as well the same as the development user?

I'm asking because right now maintaining two users adds complexity to both provisioning playbook and also development, i.e. making sure to create some files with run user permissions. We could avoid that if we had one single user for development and runtime.

**Comment by tomster** [comment]
the deployment user needs write access to our software in order to install and update it, the run user only needs read access in order to execute it.

the reasoning behind separating these is that the run user also owns the processes that connect to the outside (i.e. homeassistan, pyramid, nuimo_app etc.) and thus handle user data, IOW they are the most likely to be exploited. since the deployment user doesn't run anything during normal operations that user is less likely to be exploited remotely.

does this answer your question?

**Comment by larsblumberg** [comment]
Sounds totally reasonable to me, thanks
